name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      job:
        required: true
      comment_id:
        required: true

run-name: ${{inputs.id}} ${{inputs.jobType}} by ${{inputs.actor}}

jobs:
  digger-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status

    steps:
      - name: digger run ${{github.event.inputs.id}}
        run: echo digger run ${{ inputs.id }}
        shell: bash      
      - uses: actions/checkout@v4
      - uses: diggerhq/digger@vLatest
        with:
          setup-aws: false
          disable-locking: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}